name       : haskell-safe
version    : 0.3.17
release    : 3
source     :
    - https://hackage.haskell.org/package/safe-0.3.17/safe-0.3.17.tar.gz : 79c5c41e7151906969133ea21af9f7e8d25c18315886e23d0bdf6faa8b537e5c
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library wrapping Prelude/Data.List functions that can throw exceptions,
    such as head and !!.
description: |
    A library wrapping Prelude/Data.List functions that can throw exceptions, such as head and !!.
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
