name       : haskell-safe
version    : 0.3.14
release    : 1
source     :
    - http://hackage.haskell.org/package/safe-0.3.14/safe-0.3.14.tar.gz : db580cc748f6421e54a9a86a4cbf75c39cfc696880e31f972f99731737fdc88f
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library wrapping Prelude/Data.List functions that can throw exceptions, such as head and !!.
description: |
    A library wrapping Prelude/Data.List functions that can throw exceptions, such as head and !!.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register