name       : haskell-safe
version    : 0.3.18
release    : 4
source     :
    - https://hackage.haskell.org/package/safe-0.3.18/safe-0.3.18.tar.gz : d7775be28af83beeee2fa8921201c6b93358ba6a23a2967d53e5f382a9ec0fed
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library wrapping Prelude/Data.List functions that can throw exceptions, such as head and !!.
description: |
    A library wrapping Prelude/Data.List functions that can throw exceptions, such as head and !!.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
